PanRight:
  inference_config: "configs/inference/inference-v2.yaml"
  motion_module:
    - "models/Motion_Module/animatediffMotion_v15V2.ckpt"

  motion_module_lora_configs:
    - path:  "models/MotionLoRA/v2_lora_ZoomOut.ckpt"
      alpha: 0.4

  # dreambooth_path: "/content/drive/MyDrive/AI/sd/DreamBooth_LoRA/realisticVisionV20_v20.safetensors"
  # lora_model_path: ""

  seed:           45987230
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "background is Delicious Monastery, at Dusk, An ancient warrior woman in armour, ancient technology, deep focus, Graphic novel, Confused, Post-Apocalyptic, Bloom light, Depth of field 100mm, Amaro, RTX, make-up, mascara, ruined make-up, eyeshadow, moody atmosphere, misty, night, low light, chiaroscuro, masterpiece, best quality, (intricate details), dreamy, perfect eyes, dark pupils, magnificent, ethereal, volumetric lighting, lightroom, ((cinematic)), raytracing, subsurface scattering, face focu"

  n_prompt:
    - "(deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation. tattoo, watermark, text, anime, illustration, sketch, 3d, vector art, cartoon, painting, (large breasts, huge breasts:1.4), thick hips, thick thighs, (voluptuous, thick:1.3), fat, milf, sheer, lingerie, frills, lace"
