RollingAnticlockwise:
  inference_config: "configs/inference/inference-v2.yaml"
  motion_module:
    - "models/Motion_Module/animatediffMotion_v15V2.ckpt"

  # motion_module_lora_configs:
  #   - path:  "models/MotionLoRA/v2_lora_RollingAnticlockwise.ckpt"
  #     alpha: 1.0

  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV51_v51VAE.safetensors"
  lora_model_path: ""

  seed:           45987230
  steps:          20
  guidance_scale: 5

  prompt:
    - "photo of stunning mountain peak in Himalayas, storm weather, wind, waves, lightning, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"

  n_prompt:
    - "blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured"
