Nature:
  inference_config: "configs/inference/inference-v2.yaml"
  motion_module:
    - "models/Motion_Module/mm_sd_v15_v2.ckpt"

  motion_module_lora_configs:
    - path:  "models/MotionLoRA/v2_lora_PanRight.ckpt"
      alpha: 1.0

  # dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV51_v20Novae.safetensors"
  # lora_model_path: ""

  seed:           45987230
  steps:          20
  guidance_scale: 0

  prompt:
    - "photo of stunning mountain peak in Himalayas,award winning photo, national geography photo, best photo, lightning, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"

  n_prompt:
    - "(((low resolution))), (low quality), blur, haze, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured"
