# -------------------------
# Tiny-SD 256x256 VRAM-safe FP16 pour 5D AnimateDiff
# Avec Motion Module Tiny et VAE offload
# -------------------------
use_n3r_model: true
use_mini_gpu: false
n3r_L: 6
n3r_N_samples: 12
n3r_L_low: 4
n3r_L_high: 8
verbose: true
#L_low, L_high = 4, 8  # plus de couches = plus de structure
#final_latent_scale: 0.18215
final_latent_scale: 0.25
tile_size: 64
#--------------------latent_scale_boost 5.71 ------------
latent_injection: 1.00  # 85%
latent_scale_boost: 5.71 #0.18215 # 5.71
#
W: 512
H: 512
#W: 512
#H: 512
L: 4
steps: 50 # diffusion steps faible pour VRAM - Augmenter steps ou fps → le motion module a plus de temps pour transformer les latents. (20)

fps: 12 # moins de frames simultanées
#init_image_scale: 0.25  # Exploration maximale du latent 0. (0.25)  - Augmenter init_image_scale → donne plus de signal à partir de ton image d’initiation. (1.0 image original)
init_image_scale: 0.85  # presque tout le signal de l'image d'origine
creative_noise: 0.0    # moins de liberté, plus de cohérence
guidance_scale: 2.0      # un peu plus strict pour que le chat ressorte 8.0



# -------------------------
# Modèles n3oray
# -------------------------
# Liste des modèles à utiliser (ordre = interpolation possible) LoRA est FP16 ou compatible avec ton UNet SDXL.

n3oray_models:
  #cyberpunk_style_v3: "/mnt/62G/huggingface/cyber-fp16/cyberpunk style v3_fp16.safetensors"  #OK
  #cybersamurai_v2: "/mnt/62G/huggingface/cyber-fp16/cybersamuraiV2E12_fp16.safetensors" #OK
  #cyber_skin: "/mnt/62G/huggingface/cyber-fp16/Cyber skin_fp16.safetensors" #OK
  #cyber_skin_girl: "/mnt/62G/huggingface/cyber/cyber_style_girl_v1.safetensors" #OK

motion_module: "v3_sd15_mm.ckpt"

upscale_factor: 2

pretrained_model_path: "/mnt/62G/huggingface/miniSD"
unet_dtype: float32
dtype: float16 # VRAM safe FP16 pour 4Go-
use_real_esrgan: true

scheduler:
  type: DDIMScheduler
  #type: PNDMScheduler
  steps: 40
  beta_start: 0.00085
  beta_end: 0.012

num_fraps_per_image: 6        # plus de frames par image pour plus de cohérence
transition_frames: 0          # transitions plus douces
key_frames: 1


#80*0.6+80 = 128 → ok.
block_size: 160 #80 ou 100 ou 110 ou 120 ou (128) ou 156 ou (160 MAX soit 160x0.6+160=256)  160
overlap: 96   #40 ou 60 ou 66 ou 72 ou 76 ou (80) ou 100 ou (96)  96
vae_slicing: true
vae_tiling: true
vae_device: cpu   # force VAE sur CPU pour VRAM safe
motion_module_device: cpu
#motion_module_device: cuda

#   Vérifier le motion module → certains modules “lite” sont trop conservateurs avec des images petites ou des frames peu nombreuses.
#motion_module: scripts/modules/motion_module_tiny.py
#motion_module: scripts/modules/Motion_module_Masked.py
#motion_module: scripts/modules/Motion_module_Enhanced.py
motion_module: scripts/modules/Motion_module_Wind.py
#motion_module: scripts/modules/motion_module_lite.py
#motion_module: scripts/modules/motion_module_ultralite_debug.py
#motion_module: scripts/modules/motion_ulta_lite_fix.py
#motion_module: scripts/modules/motion_module_show.py (test ok)

device: cuda
offload_folder: /tmp/offload
accelerate: true
low_cpu_mem_usage: true
batch_size: 1  # chaque image traitée individuellement

seed: 1234

enable_xformers_memory_efficient_attention: true

# VAE complet pour couleurs correctes
#vae_path: "/mnt/62G/huggingface/vae/vae-ft-mse-840000-ema-pruned.safetensors"
#vae_path: "/mnt/62G/huggingface/vae/vaeKlF8Anime2_klF8Anime2VAE.safetensors"
#vae_path: "/mnt/62G/huggingface/miniSD-fp16/vae/diffusion_pytorch_model_fp16.safetensors"
vae_path: "/mnt/62G/huggingface/miniSD-fp16/vae/diffusion_pytorch_model.safetensors"
#vae_path: "/mnt/62G/huggingface/miniSD-fp16/vae"



prompt:
  - "Cute little kawaii cat, big sparkling eyes, small  nose, fluffy fur, sitting, happy expression, pastel colors, soft lighting, anime style, chibi, simple background, fluffy, velvety fur, soft texture, gentle sparkles around, cozy atmosphere"
  - "Cute little kawaii cat, big sparkling eyes, big nose, fluffy fur, sitting, happy expression, pastel colors, high lighting, anime style, chibi, simple background, soft morning light, warm ambient, subtle rim light, glowing eyes"

n_prompt:
  - "blurry, deformed, extra limbs, bad anatomy, low quality, messy background, dark colors, scary, realistic, human features"
  - "blurry, deformed, extra limbs, bad anatomy, low quality, messy background, dark colors, scary, realistic, human features, accurate anatomy, correct proportions, four paws visible, cute rounded ears"

input_images:
  - "input/divers/image_512x.png"
  - "input/divers/1.png"

